spring:
  application:
    name: ollama-service
server:
  port:
    8082
ollama:
  base-url: http://localhost:11434
  model: llama3.2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true