services:
  reviewapp-db:
    image: postgres:15
    networks:
      - reviewapp-network
    environment:
      POSTGRES_USER: user  # Nombre de usuario
      POSTGRES_PASSWORD: pass  # Contraseña
      POSTGRES_DB: review-db  # Nombre de la base de datos
    ports:
      - "5432:5432"
    volumes:
      - reviewapp_data:/var/lib/postgresql/data

networks:
  reviewapp-network:
volumes:
  reviewapp_data:
